source :gemcutter

gem 'RedCloth',         '4.1.1'
gem 'aasm',             '2.1.5'
gem 'activerecord-oracle_enhanced-adapter', '1.2.4'
gem 'bcdatabase',       '1.0.1'
gem 'bluecloth',        '2.0.7'
#gem 'bundler',         '0.9.24'
gem 'capistrano',       '2.5.2'
gem 'creditcard',       '1.0'
gem 'mime-types',       '1.16', :require => "mime/types"
gem 'paperclip',        '2.3.1.1'
gem 'rails',            '2.3.5'
gem 'rake',             '0.8.7'
gem 'ruby-oci8',        '2.0.4'
gem 'haml',             '2.2.17'
gem 'spreadsheet',      '0.6.4.1'
gem 'surveyor'
gem 'vestal_versions',  '1.3.0', :git => 'git://github.com/rsim/vestal_versions.git'
gem 'will_paginate',    '2.3.15'
gem 'fast-aes',         '0.1.1'
gem 'pdf-reader',       '0.8.6'
gem 'prawn',            '0.11.1.pre'
gem 'prawnto',          '0.0.3'
gem 'fastercsv',        '1.5.3'
gem 'devise',           '1.0.9'
gem 'cancan',           '1.5.1'
gem 'devise_ldap_authenticatable', '0.1.6', :git => 'https://github.com/cschiewek/devise_ldap_authenticatable.git', :tag => '0.1.6'

group :development do
   gem 'rspec', '1.3.0'
   gem 'rspec-rails', '1.3.2'
   gem 'spork', '0.7.5'
   gem 'ZenTest', '4.2.1'
   gem 'autotest', '4.2.5'
   gem 'autotest-rails', '4.1.0'
   gem 'mocha', '0.9.7'
   gem 'thoughtbot-factory_girl', '1.2.2'
   gem 'thoughtbot-shoulda', '2.10.2'
   gem 'ruby-debug', '0.10.3'
   gem 'ruby-debug-ide', '0.4.15'
   gem 'single_test'
end
