class AddMissingForeignKeys < ActiveRecord::Migration
  def change
    add_foreign_key "account_users", "users", name: "account_users_user_id_fk"
    add_foreign_key "accounts", "affiliates", name: "accounts_affiliate_id_fk"
    add_foreign_key "external_service_passers", "external_services", name: "external_service_passers_external_service_id_fk"
    add_foreign_key "external_service_receivers", "external_services", name: "external_service_receivers_external_service_id_fk"
    add_foreign_key "journal_rows", "journals", name: "journal_rows_journal_id_fk"
    add_foreign_key "journal_rows", "order_details", name: "journal_rows_order_detail_id_fk"
    add_foreign_key "journals", "users", name: "journals_created_by_fk", column: "created_by"
    add_foreign_key "journals", "facilities", name: "journals_facility_id_fk"
    add_foreign_key "notifications", "users", name: "notifications_user_id_fk"
    add_foreign_key "order_details", "users", name: "order_details_assigned_user_id_fk", column: "assigned_user_id"
    add_foreign_key "order_details", "users", name: "order_details_created_by_fk", column: "created_by"
    add_foreign_key "order_details", "journals", name: "order_details_journal_id_fk"
    add_foreign_key "order_details", "order_statuses", name: "order_details_order_status_id_fk"
    add_foreign_key "order_details", "statements", name: "order_details_statement_id_fk"
    add_foreign_key "order_imports", "users", name: "order_imports_created_by_fk", column: "created_by"
    add_foreign_key "order_imports", "stored_files", name: "order_imports_error_file_id_fk", column: "error_file_id"
    add_foreign_key "order_imports", "stored_files", name: "order_imports_upload_file_id_fk", column: "upload_file_id"
    add_foreign_key "order_statuses", "facilities", name: "order_statuses_facility_id_fk"
    add_foreign_key "order_statuses", "order_statuses", name: "order_statuses_parent_id_fk", column: "parent_id"
    add_foreign_key "orders", "users", name: "orders_created_by_fk", column: "created_by"
    add_foreign_key "orders", "orders", name: "orders_merge_with_order_id_fk", column: "merge_with_order_id"
    add_foreign_key "orders", "order_imports", name: "orders_order_import_id_fk"
    add_foreign_key "orders", "users", name: "orders_user_id_fk"
    add_foreign_key "price_group_members", "accounts", name: "price_group_members_account_id_fk"
    add_foreign_key "price_group_members", "users", name: "price_group_members_user_id_fk"
    add_foreign_key "price_group_products", "price_groups", name: "price_group_products_price_group_id_fk"
    add_foreign_key "price_group_products", "products", name: "price_group_products_product_id_fk"
    add_foreign_key "price_policies", "products", name: "price_policies_product_id_fk"
    add_foreign_key "product_access_groups", "products", name: "product_access_groups_product_id_fk"
    add_foreign_key "product_access_schedule_rules", "product_access_groups", name: "product_access_schedule_rules_product_access_group_id_fk"
    add_foreign_key "product_access_schedule_rules", "schedule_rules", name: "product_access_schedule_rules_schedule_rule_id_fk"
    add_foreign_key "product_accessories", "products", name: "product_accessories_accessory_id_fk", column: "accessory_id"
    add_foreign_key "product_accessories", "products", name: "product_accessories_product_id_fk"
    add_foreign_key "product_users", "product_access_groups", name: "product_users_product_access_group_id_fk"
    add_foreign_key "product_users", "users", name: "product_users_user_id_fk"
    add_foreign_key "products", "order_statuses", name: "products_initial_order_status_id_fk", column: "initial_order_status_id"
    add_foreign_key "relays", "products", name: "relays_instrument_id_fk", column: "instrument_id"
    add_foreign_key "reservations", "users", name: "reservations_canceled_by_fk", column: "canceled_by"
    add_foreign_key "statement_rows", "order_details", name: "statement_rows_order_detail_id_fk"
    add_foreign_key "statement_rows", "statements", name: "statement_rows_statement_id_fk"
    add_foreign_key "statements", "accounts", name: "statements_account_id_fk"
    add_foreign_key "statements", "users", name: "statements_created_by_fk", column: "created_by"
    add_foreign_key "stored_files", "users", name: "stored_files_created_by_fk", column: "created_by"
    add_foreign_key "user_roles", "facilities", name: "user_roles_facility_id_fk"
    add_foreign_key "user_roles", "users", name: "user_roles_user_id_fk"
  end
end
